# Generated by Django 3.2.4 on 2021-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('non_enc_key', models.CharField(blank=True, default='', max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
